musicTrainee/catalog/urls.py
from django.urls import path

from .views import base_view, CourseModules
from .views import CoursesListView, CourseDetails, CourseModuleDetails

app_name = "catalog"

urlpatterns = [
    path("", base_view, name="base-page"),
    path("catalog/", CoursesListView.as_view(), name="base-page"),
    path("catalog/<str:slug>/", CourseDetails.as_view(), name="course-details"),
    path("catalog/<str:slug>/modules/", CourseModules.as_view(), name="course-modules"),
    path("catalog/<str:slug>/modules/<int:module_id>/", CourseModules.as_view(), name="course-modules"),
    path("catalog/<str:slug>/modules/<int:module_id>/<int:pk>/", CourseModuleDetails.as_view(), name="course-modules-details"),
]

musicTrainee/musicTrainee/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('api/', include('musicApi.urls')),

    # Путь для документации.
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/docs/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),

    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT,
    )
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT,
    )

musicTrainee/catalog/models.py
from typing import TYPE_CHECKING

from django.db import models
from django.db.models import Manager
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.db.models.signals import post_delete
from django.dispatch import receiver

from .fields import OrderField
from django.conf import settings


class CourseRating(models.Model):
    """
    Модель для отзывов на курс
    """
    course = models.ForeignKey("Course", related_name='ratings', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='ratings', on_delete=models.CASCADE)
    rating = models.PositiveIntegerField()
    review = models.TextField(blank=True, null=True)

    class Meta:
        unique_together = ('course', 'user')


def course_logo_directory_path(instance: "Course", filename: str) -> str:
    """
    Функция определения пути логотипа курса.

    :param instance: Экземпляр модели Course.
    :param filename: Название файла.
    :return: Путь для сохранения логотипа.
    """
    return "courses/course_{pk}/logo/{filename}".format(
        pk=instance.pk,
        filename=filename
    )


def course_images_directory_path(instance: "Course", filename: str) -> str:
    """
    Функция определения пути изображения для занятий.

    :param instance: Экземпляр модели Course.
    :param filename: Название файла.
    :return: Путь для сохранения изображений.
    """
    return "courses/course_{pk}/images/{filename}".format(
        pk=instance.pk,
        filename=filename
    )


def course_files_directory_path(instance: "Course", filename: str) -> str:
    """
    Функция определения пути прикладных файлов.

    :param instance: Выбранный курс.
    :param filename: Название файла.
    :return: Путь для сохранения файлов.
    """
    return "courses/course_{pk}/files/{filename}".format(
        pk=instance.pk,
        filename=filename
    )


class Course(models.Model):
    """
    Модель курса.
    """
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="courses_creator", on_delete=models.CASCADE)
    owner = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name="courses_owner")
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField()
    target_description = models.CharField(max_length=500)
    price = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    created = models.DateTimeField(auto_now_add=True)
    logo = models.ImageField(null=True, blank=True, upload_to=course_logo_directory_path)
    approval = models.BooleanField(default=False)

    def average_rating(self):
        ratings = self.ratings.all()
        if ratings.exists():
            return ratings.aggregate(models.Avg('rating'))['rating__avg']

    def __str__(self):
        return f"{self.title}"

    if TYPE_CHECKING:
        objects: Manager


class Module(models.Model):
    """
    Модель модуля курса.
    """
    course = models.ForeignKey(Course, related_name='modules', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    order = OrderField(blank=True, for_fields=['course'])

    if TYPE_CHECKING:
        objects: Manager

    def __str__(self):
        return f'{self.order}. {self.title}'

    class Meta:
        ordering = ['order']


class Lesson(models.Model):
    module = models.ForeignKey(Module, related_name='lessons', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    order = OrderField(blank=True, for_fields=['module'])

    if TYPE_CHECKING:
        objects: Manager

    def __str__(self):
        return f'{self.order}. {self.title}'

    class Meta:
        ordering = ['order']


class Content(models.Model):
    """
    Модель контента курса.
    """
    lesson = models.ForeignKey(Lesson, related_name='contents', on_delete=models.CASCADE)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE,
                                     limit_choices_to={
                                         'model__in':
                                             (
                                                 'text',
                                                 'video',
                                                 'image',
                                                 'file',
                                                 'question',
                                                 'task',
                                             )
                                     }
                                     )
    object_id = models.PositiveIntegerField()
    item = GenericForeignKey('content_type', 'object_id')
    order = OrderField(blank=True, for_fields=['lesson'])

    if TYPE_CHECKING:
        objects: Manager

    class Meta:
        ordering = ['order']

    def __str__(self):
        return str(self.item)


class ItemBase(models.Model):
    """
    Абстрактная базовая модель контента.
    """
    title = models.CharField(max_length=250)

    class Meta:
        abstract = True

    def __str__(self):
        return self.title


class Text(ItemBase):
    """
    Модель текстового контента.
    """
    content = models.TextField()


class File(ItemBase):
    """
    Модель файла контента.
    """
    file = models.FileField(upload_to=course_files_directory_path)

    def delete(self, *args, **kwargs):
        storage, path = self.file.storage, self.file.path
        super(File, self).delete(*args, **kwargs)
        storage.delete(path)


class Image(ItemBase):
    """
    Модель изображения контента.
    """
    file = models.FileField(upload_to=course_images_directory_path)


class Video(ItemBase):
    """
    Модель видео контента.
    """
    url = models.URLField()


class Question(ItemBase):
    """
    Модель текста вопроса теста.
    """
    text = models.TextField(max_length=3000, verbose_name="text_question", blank=True, null=True)

    # def __str__(self):
    #     return self.text


class Answer(models.Model):
    """
    Модель текста ответа теста.
    """
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=300)
    is_true = models.BooleanField(default=False)

    # def __str__(self):
    #     return self.text


def course_tasks_directory_path(instance: "Course", filename: str):
    """
    Функция определения пути сохранения заданий курса.

    :param instance: Экземпляр модели Course.
    :param filename: Название файла.
    :return: Путь для сохранения файла.
    """
    return "courses/course_{pk}/tasks/{filename}".format(
        pk=instance.pk,
        filename=filename
    )


class Task(ItemBase):
    """
    Модель задания курса.
    """
    description = models.TextField()

    def __str__(self):
        return f"{self.title}"

    if TYPE_CHECKING:
        objects: Manager


class TaskSubmission(models.Model):
    """
    Модель для прикрепления файла для проверки задания
    """
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name="submissions")
    student = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="submissions")
    file = models.FileField(upload_to=course_tasks_directory_path)
    submitted_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("task", "student")
        ordering = ["-submitted_at"]

    if TYPE_CHECKING:
        objects: Manager


class TaskReview(models.Model):
    """
    Модель для ответа на домашнее задание пользователя
    """
    task_submission = models.ForeignKey(TaskSubmission, on_delete=models.CASCADE, related_name="review")
    is_correct = models.BooleanField(null=True, default=None)
    comment = models.TextField(blank=True)

    if TYPE_CHECKING:
        objects: Manager


def comments_content_directory_path(instance: "Comment", filename: str):
    ...


class CommentContent(models.Model):
    """
    Модель комментария к занятию
    """
    content = models.ForeignKey(Content, related_name="comments", on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text = models.TextField()
    # attach_file = models.FileField(upload_to=comments_content_directory_path)


@receiver(post_delete, sender=File)
def auto_delete_file(sender, instance, **kwargs):
    if instance.file:
        instance.file.delete(False)

musicTrainee/catalog/forms.py
from django import forms

musicTrainee/catalog/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView

from .models import Course, Module, Content


def base_view(request: HttpRequest):
    queryset = {
        "courses": Course.objects.select_related("creator").prefetch_related("owner").all(),
        "modules": Module.objects.select_related("course").all()
    }
    return render(request=request, template_name='catalog/base.html', context=queryset)
    # return HttpResponse("Какой-то каталог")


class CoursesListView(ListView):
    queryset = Course.objects.select_related("creator").all()
    context_object_name = "courses"
    template_name = "catalog/course-catalog.html"


class CourseDetails(DetailView):
    template_name = "catalog/course-details.html"
    queryset = Course.objects.select_related("creator")
    context_object_name = "course"


class CourseModules(ListView):
    def get_queryset(self):
        course_slug = self.request.path.split('/')[2]
        course_choice = Course.objects.filter(slug=course_slug)[0]
        queryset_modules = Module.objects.select_related("course").filter(course=course_choice).all()

        queryset_modules_content = dict()
        # queryset_content = Content.objects.select_related("module").filter(module=queryset_modules).all()

        # queryset_content = dict()
        for module in queryset_modules:
            content_module = Content.objects.filter(module=module).all()
            queryset_modules_content[module] = content_module
            for content_object in content_module:
                print(content_object.item)

        # print(queryset_modules_content)

        queryset = {
            "course": course_choice,
            "content": queryset_modules_content,
        }
        return queryset

    context_object_name = "objects"
    template_name = "catalog/course-modules.html"


class CourseModuleDetails(DetailView):
    # model = Module
    context_object_name = "course"
    template_name = "catalog/course-modules-details.html"

    # def get_object(self, queryset=None):
    #     course_content_pk = self.request.path.split('/')[4]
    #     queryset = Content.objects.filter(pk=course_content_pk).all()
    #     return queryset

    def get_object(self, queryset=None):
        course = get_object_or_404(Course, slug=self.kwargs["slug"])
        # module = get_object_or_404(Module, pk=self.kwargs["pk"], course=course)
        return course

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        course = self.object
        content = get_object_or_404(Content, pk=self.kwargs['pk'], module__course=course)
        context['content'] = content
        return context

musicTrainee/catalog/templates/catalog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h3><a href="api/docs/">API docs</a></h3>
    <h3><a href="admin/">Admin panel</a></h3>
</body>
</html>

musicTrainee/catalog/templates/catalog/course-catalog.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Courses</title>
</head>
<body>
    <h1>Какие-то курсы</h1>
{#    {{ courses }}#}
    <ul>
        {% for course in courses %}
{#        	<li>{{ course.pk }}</li>#}
{#        	<li>{{ course.title }}</li>#}
            <li><a href="{% url 'catalog:course-details' slug=course.slug %}">{{ course.title }}</a></li>
            <li><img src="{{ course.logo.url }}" alt="Not found logo"></li>
            <li>{{ course.creator }}</li>
            <li>{{ course.description }}</li>
            <li>{{ course.price }} р.</li>
{#            <li>{{ course.modules.all }}</li>#}
{#            {% for module in course.modules.all %}#}
{#                Модули:#}
{#                <ul>#}
{#            	    <li>{{ module.title }}</li>#}
{##}
{#                    <li>{{ module.contents.all }}</li>#}
{#                    <ul>#}
{#                        {% for content in module.contents.all %}#}
{##}
{#                            <li>{{ content.item.title }}</li>#}
{#                            <li>{{ content.item.content }}</li>#}
{##}
{#                        {% endfor %}#}
{#                    </ul>#}

{#                </ul>#}
{#            {% endfor %}#}

{#            {% for owner in course.owner.all %}#}
{#                Владельцы:#}
{#                <ul>#}
{#                    <li>{{ owner }}</li>#}
{#                </ul>#}
{#            {% endfor %}#}

            <li>{{ course.approval }}</li>
            <br>
        {% endfor %}
    </ul>
</body>
</html>

musicTrainee/catalog/templates/catalog/course-details.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Courses</title>
</head>
<body>
    <h1>{{ course }}</h1>

    <ul>
        <li><b>Название курса:</b>{{ course.title }}</li>
        <li><img src="{{ course.logo.url }}" alt="Not found logo"></li>
        <li><b>Описание:</b><br>{{ course.description }}</li>

        <li><b><a href="{% url 'catalog:course-modules' slug=course.slug %}">Модули</a></b></li>

        <li><b>Цена: </b>{{ course.price }}р.</li>
        <li><b>Создатель:</b> {{ course.creator }}</li>
    </ul>

</body>
</html>

musicTrainee/catalog/templates/catalog/course-modules-details.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Modules</title>
</head>
<body>


<h1>{{ content.item }}</h1>

{% if content.item.content %}
    <p>{{ content.item.content }}</p>
{#{% elif content.item.text %}#}
{% endif %}
{#{{ content.item.answer_set.all }}#}
{% for answer in content.item.answer_set.all %}
	<p>{{ answer }}</p>
{% endfor %}





</body>
</html>

musicTrainee/catalog/templates/catalog/course-modules.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Modules</title>
</head>
<body>
    <h1>{{ objects.course }}</h1>

    {% for module, contents in objects.content.items %}
    	<h2>{{ module.title }}</h2>
        {% for content in contents %}
            <h3><a href="{% url 'catalog:course-modules-details' slug=objects.course.slug pk=content.pk %}">{{ content.item }}</a></h3>
        {% endfor %}

    {% endfor %}


</body>
</html>